#include "iostream"
using namespace std;
int main(){
	string s;
	int i,j;
	while(cin>>s){
		int head=-1,dian=-1;
		string result="";
	   for(i=0;s[i]!='\0';i++){
	   	    if(s[i]=='.'){
	   	    	dian=i;
	   	    	break;
	   	    }
	   	    if(head==-1&&s[i]!='0'&&s[i]!='-')
	   	    head=i;
	   }
	  if(head==-1){
	     if(dian==-1){
	     	if(s[0]=='-')
	     	cout<<"(0.00)"<<endl;
	     	else
	     	cout<<"0.00"<<endl;
	     	continue;
	     }
      else{
      	head=dian-1;
      }	
}
	   if(dian==-1){
	   	   if(s[0]=='-'){
	   	   	  result=".00)";
	   	   	  for(i=s.length()-1,j=1;i>=head;i--,j++){
	   	   	     if(j%4==0){
	   	   	     	j=1;
	   	   	     	result=','+result;
	   	   	     }
	   	   	       result=s[i]+result;
	   	   	 }
	   	   	 result='('+result;
	   	   	   cout<<result<<endl;
	   	   }
	   	   else{
	   	   	  result=".00";
	   	   	  for(i=s.length()-1,j=1;i>=head;i--,j++){
	   	   	     if(j%4==0){
	   	   	     	j=1;
	   	   	     	result=','+result;
	   	   	     }
	   	   	       result=s[i]+result;
	   	   	 }
	   	   	   cout<<result<<endl;
	   	   }
	   }	
	   else{
	   	if(s[0]=='-'){
	   		result=")";
	   		if(s.length()-dian<4){
	   			if(s.length()-dian==3){
	   	   	   for(i=s.length()-1;i>=dian;i--)
	   	   	   result=s[i]+result;	 
	   	   }
					 else if(s.length()-dian==2){
					 	result='0'+result;	 
					 	 for(i=s.length()-1;i>=dian;i--)
	   	   	           result=s[i]+result;	 
					 }  						    	   
	   	   }
	   	    else{
			   //处理四舍五入
			   if(s[dian+3]>='5'){
			   	  s[dian+2]+=1;
			   } 
			   j=dian+2;
			   while(s[j]>'9'&&j>=head){
			   	  s[j]='0';
			   	  if(j-1==dian)
                      j--;
			   	  s[j-1]++;
			   	  j--;
			   }
			   if(s[head]=='0'&&j==head){
			    head--;	   	
			    s[head]='1';
			}
			    for(i=dian+2;i>=dian;i--)
	   	   	   result=s[i]+result;	
	   	    }
	   	    for(i=dian-1,j=1;i>=head;i--,j++){
	   	   	     if(j%4==0){
	   	   	     	j=1;
	   	   	     	result=','+result;
	   	   	     }
	   	   	       result=s[i]+result;
	   	   	 }
	   	   	 result='('+result;
	   	   	   cout<<result<<endl;
	   	   }
	   	   else{
	   		if(s.length()-dian<4){
	   			if(s.length()-dian==3){
	   	   	   for(i=s.length()-1;i>=dian;i--)
	   	   	   result=s[i]+result;	
				}
			  else if(s.length()-dian==2){
					 	result='0'+result;	 
					 	 for(i=s.length()-1;i>=dian;i--)
	   	   	           result=s[i]+result;	 
					 }  	
	   	   }
	   	    else{
			   //处理四舍五入
			   if(s[dian+3]>='5'){
			   	  s[dian+2]+=1;
			   } 
			   j=dian+2;
			   while(s[j]>'9'&&j>=head){
			   	  s[j]='0';
			   	  if(j-1==dian)
                      j--;
			   	  s[j-1]++;
			   	  j--;
			   }
			   if(s[head]=='0'&&j==head){
			    head--;	   	
			    s[head]='1';
			}
			    for(i=dian+2;i>=dian;i--)
	   	   	   result=s[i]+result;	
	   	    }
	   	    for(i=dian-1,j=1;i>=head;i--,j++){
	   	   	     if(j%4==0){
	   	   	     	j=1;
	   	   	     	result=','+result;
	   	   	     }
	   	   	       result=s[i]+result;
	   	   	 }
	   	   	   cout<<result<<endl;
	   	   }
	   }
	}
	return 0;
}
